import { useState } from "react";

function C1(ozellikler) {
    const [meyve, meyveyiGuncelle] = useState("Elma");

    
    console.log("C1 tekrar çalıştı");
    //...
    //...
    //...
    //...
    //...
    //...
    //...
    //...


    return <div>
        Ben C1, merhaba {ozellikler.ad}. Bu günün meyvesi: {meyve}  
        <button onClick={()=>{meyveyiGuncelle("Armut")}}>Meyve Guncelle</button>
    </div>
}

export default C1;